### ISSUE TITLE
Switch between languages (drop-down menu) doesn't always work

### ISSUE THREAD

**Issue by espensj** [global-asp/asp-imagebank#2]
The drop-down language menu often throws me back to "krokodille" in Norwegian (when I click the link Liam sent me) or English otherwise. It's like it's reverting to the default every time.

**Comment by dohliam** [comment]
Hi, thanks for reporting this. After playing around with it a bit it looks like we need to work on the switcher logic. I'll try to take a look at this in the next day or two.

**Comment by dohliam** [comment]
Issue moved to the [imagebank-explorer repo](https://github.com/dohliam/imagebank-explorer/issues/1).
